inherit_from: .rubocop_todo.yml

inherit_gem:
  theforeman-rubocop:
    - lenient.yml
    - minitest.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.2
  Exclude:
    - 'node_modules/**/*'

Bundler/OrderedGems:
  Enabled: false

# Don't enforce documentation
Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Layout/LineLength:
  Max: 120

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Rails/HelperInstanceVariable:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
